site_name: "mkdocstrings"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://pawamoy.github.io/mkdocstrings"
repo_url: "https://github.com/pawamoy/mkdocstrings"
repo_name: "pawamoy/mkdocstrings"

nav:
  - Overview: index.md
  - Usage: usage.md
  - Handlers:
    - Overview: handlers/overview.md
    - Python: handlers/python.md

  - API Reference:
      - handlers:
          - __init__.py: reference/handlers/__init__.md
          - python.py: reference/handlers/python.md
      - extension.py: reference/extension.md
      - plugin.py: reference/plugin.md
      - references.py: reference/references.md

  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
          selection:
            new_path_syntax: yes
      watch:
        - src/mkdocstrings
