site_name: "mkdocstrings"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://mkdocstrings.github.io/"
repo_url: "https://github.com/mkdocstrings/mkdocstrings"
repo_name: "mkdocstrings/mkdocstrings"

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Usage:
  - Usage: usage.md
  - Handlers:
    - Overview: handlers/overview.md
    - Python: handlers/python.md
  - Troubleshooting: troubleshooting.md
- Code Reference:
  - mkdocstrings:
    - handlers:
      - base.py: reference/handlers/base.md
      - rendering.py: reference/handlers/rendering.md
      - python.py: reference/handlers/python.md
    - extension.py: reference/extension.md
    - plugin.py: reference/plugin.md
  - mkdocs_autorefs:
    - references.py: reference/autorefs/references.md
    - plugin.py: reference/autorefs/plugin.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.expand
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- coverage:
    html_report_dir: build/coverage
- macros:
    module_name: docs/macros
    j2_variable_start_string: "[["
    j2_variable_end_string: "]]"
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append("docs")
        selection:
          new_path_syntax: yes
    watch:
    - src/mkdocstrings
